(define-key company-mode-map (kbd "<tab>")
  'company-indent-or-complete-common)
(define-key company-active-map (kbd "<tab>")
  'company-select-next-if-tooltip-visible-or-complete-selection)
(define-key company-active-map (kbd "S-<tab>")
  'company-select-previous)
(define-key company-active-map (kbd "C-n")
  'company-select-next)
(define-key company-active-map (kbd "C-p")
  'company-select-previous)
