#+TITLE: spacemacs-scratch layer

#+TAGS: layer|emacs|spacemacs

* Table of Contents                                        :TOC_5_gh:noexport:
- [[#description][Description]]
  - [[#features][Features:]]
  - [[#customizations][Customizations:]]
- [[#install][Install]]
- [[#key-bindings][Key bindings]]

* Description
This layer makes your =*scratch*= buffer persistent and not killable.

** Features:
This layer makes your =*scratch*= buffer persistent and not killable.
That makes sense if you want to save your drafts in =*scratch*= buffer temporarily.
Things you write down in =*scratch*= buffer will be automatically saved and restored.

Packages used by this layer:
[[https://github.com/Fanael/persistent-scratch][persistent-scratch]], [[https://github.com/EricCrosson/unkillable-scratch][unkillable-scratch]]

** Customizations:
You can customize this layer by setting variables of package [[https://github.com/Fanael/persistent-scratch][persistent-scratch]] and [[https://github.com/EricCrosson/unkillable-scratch][unkillable-scratch]].

* Install
To use this configuration layer, add it to your =~/.spacemacs=. You will need to
add =scratch= to the existing =dotspacemacs-configuration-layers= list in this
file.

* Key bindings

| Key Binding | Description                       |
|-------------+-----------------------------------|
| C-x C-s     | save *scratch* buffer temporarily |
| C-x C-w     | write *scratch* buffer to a file  |

See URL: https://github.com/Fanael/persistent-scratch
